services:
  - type: web
    name: riskapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    plan: free
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URI
        value: sqlite:////data/riskapp.db
